name: digit_to_words_bd
description: A package to convert digits to words.
version: 1.0.1
homepage: https://github.com/Raz4492
repository: https://github.com/Raz4492/digittowords/tree/main/PackageFlutter/digittowords

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
