name: digittowords
description: A package to convert digits to words.
version: 1.0.0

homepage: https://github.com/Raz4492/digittowords

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

# dependencies:
#   path: ^1.8.0
flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
